version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - automated
    groups:
      python-minor-patch:
        update-types:
          - minor
          - patch
      python-major:
        update-types:
          - major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - automated
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch
      actions-major:
        update-types:
          - major

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - automated
